name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # 毎週月曜日の午前9時（JST）に実行
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  backend-security:
    name: Backend Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: ./backend
        run: |
          poetry install --with dev

      - name: Run Safety check
        working-directory: ./backend
        run: |
          poetry run safety check --json || true
        continue-on-error: true

      - name: Run Safety check (detailed)
        working-directory: ./backend
        run: |
          poetry run safety check --full-report
        continue-on-error: true

  frontend-security:
    name: Frontend Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run npm audit
        working-directory: ./frontend
        run: |
          npm audit --production --json > audit-report.json || true
          cat audit-report.json
        continue-on-error: true

      - name: Run npm audit (detailed)
        working-directory: ./frontend
        run: |
          npm audit --production
        continue-on-error: true

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: npm-audit-report
          path: ./frontend/audit-report.json
